[package]
name = "ungit"
version = "0.1.1"
edition = "2024"

[dependencies]
clap = "4.5.38"
flate2 = "1.1.1"
reqwest = { version = "0.12.15", features = [] }
tar = "0.4.44"
tokio = { version = "1.45.0", features = ["full"] }
